import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "700"], // Add more weights as needed
  variable: "--font-raleway", // Optional: if you want to use it as a CSS variable
});

export const metadata: Metadata = {
  title: "BkWellness",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-amber-50 md:bg-white border-none ">
      <body className={`${raleway.className} antialiased m-0 p-0`}>
        {children}
      </body>
    </html>
  );
}
